from __future__ import annotations

import os
import shlex
import sys
from pathlib import Path


def wrapper_path() -> Path:
    return Path.home() / ".local" / "lib" / "xenon" / "panic-trigger"


def xenon_invocation() -> list[str]:
    """Absolute argv that launches Xenon regardless of PATH or install layout."""
    candidates: list[Path] = []

    argv0 = Path(sys.argv[0]).expanduser()
    if argv0.name not in {"", "-c", "-m"}:
        if not argv0.is_absolute():
            maybe = Path.cwd() / argv0
            if maybe.exists():
                candidates.append(maybe.resolve())
        elif argv0.exists():
            candidates.append(argv0.resolve())

    exe_dir = Path(sys.executable).resolve().parent
    candidates.append(exe_dir / "xenon")

    xdg_bin = os.environ.get("XDG_BIN_HOME")
    if xdg_bin:
        candidates.append(Path(xdg_bin).expanduser() / "xenon")
    candidates.append(Path.home() / ".local" / "bin" / "xenon")
    candidates.append(Path("/usr/local/bin/xenon"))
    candidates.append(Path("/usr/bin/xenon"))

    env_path = os.environ.get("PATH", "")
    for item in env_path.split(os.pathsep):
        if not item:
            continue
        binary = Path(item).expanduser() / "xenon"
        if binary.exists():
            candidates.append(binary.resolve())

    seen: set[str] = set()
    for path in candidates:
        try:
            resolved = path.resolve()
        except OSError:
            continue
        key = str(resolved)
        if key in seen:
            continue
        seen.add(key)
        if resolved.is_file() and os.access(resolved, os.X_OK):
            return [key]

    python = str(Path(sys.executable).resolve())
    return [python, "-m", "xenon"]


def panic_command() -> list[str]:
    return [*xenon_invocation(), "panic", "--trigger"]


def write_panic_wrapper(path: Path | None = None) -> Path:
    """Shell wrapper with an absolute path so compositor binds do not need PATH."""
    invocation = " ".join(shlex.quote(part) for part in panic_command())
    path = (path or wrapper_path()).expanduser()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "#!/bin/sh\n"
        "# Generated by Xenon. Do not edit; re-run: xenon install-trigger\n"
        f"exec {invocation}\n",
        encoding="utf-8",
    )
    path.chmod(0o755)
    return path.resolve()
